global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Data;
global using Microsoft.UI.Xaml.Markup;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Media.Imaging;
global using Microsoft.UI.Xaml.Shapes;
global using System;
global using System.Threading.Tasks;
global using Windows.Foundation;
global using Windows.UI;
global using Path = Microsoft.UI.Xaml.Shapes.Path;
