global using Microsoft.UI;
global using Microsoft.UI.Input;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Data;
global using Microsoft.UI.Xaml.Input;
global using Microsoft.UI.Xaml.Markup;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Media.Imaging;
global using Microsoft.UI.Xaml.Shapes;
global using Microsoft.Windows.Widgets.Providers;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.InteropServices;
global using Windows.Foundation;
global using Windows.Storage;
global using Windows.UI;
global using WinRT;
global using Path = Microsoft.UI.Xaml.Shapes.Path;
